package net.lostillusion.kypixel.api.entities

enum class GameType(val id: Int, val typeName: String, val databaseName: String, val cleanName: String) {
    QUEUE(-6, "QUEUE", "QUEUE", "Queue"),
    IDLE(-5, "IDLE", "IDLE", "Idle"),
    LIMBO(-4, "LIMBO", "LIMBO", "Limbo"),
    REPLAY(-3, "REPLAY", "REPLAY", "Replay"),
    MAIN_LOBBY(-2, "MAIN_LOBBY", "MAIN_LOBBY", "Main Lobby"),
    TOURNAMENT_LOBBY(-1, "TOURNAMENT_LOBBY", "TOURNAMENT_LOBBY", "Tournament Lobby"),
    QUAKECRAFT(2, "QUAKECRAFT", "Quake", "Quake"),
    WALLS(3, "WALLS", "Walls", "Walls"),
    PAINT_BALL(4, "PAINTBALL", "Paintball", "Paintball"),
    SURVIVAL_GAMES(5, "SURVIVAL_GAMES", "HungerGames", "Blitz Survival Games"),
    TNT_GAMES(6, "TNTGAMES", "TNTGames", "TNT Games"),
    VAMPIREZ(7, "VAMPIREZ", "VampireZ", "VampireZ"),
    MEGA_WALLS(13, "WALLS3", "Walls3", "Mega Walls"),
    ARCADE(14, "ARCADE", "Arcade", "Arcade"),
    ARENA(17, "ARENA", "Arena", "Arena"),
    UHC(20, "UHC", "UHC", "UHC Champions"),
    COPS_AND_CRIMS(21, "MCGO", "MCGO", "Cops and Crims"),
    WARLORDS(23, "BATTLEGROUND", "Battleground", "Warlords"),
    SMASH_HEROES(24, "SUPER_SMASH", "SuperSmash", "Smash Heroes"),
    TURBO_KART_RACERS(25, "GINGERBREAD", "GingerBread", "Turbo Kart Racers"),
    HOUSING(26, "HOUSING", "Housing", "Housing"),
    SKYWARS(51, "SKYWARS", "SkyWars", "SkyWars"),
    CRAZY_WALLS(52, "TRUE_COMBAT", "TrueCombat", "Crazy Walls"),
    SPEED_UHC(54, "SPEED_UHC", "SpeedUHC", "Speed UHC"),
    SKYCLASH(55, "SKYCLASH", "SkyClash", "SkyClash"),
    CLASSIC_GAMES(56, "LEGACY", "Legacy", "Classic Games"),
    PROTOTYPE(57, "PROTOTYPE", "Prototype", "Prototype"),
    BED_WARS(58, "BEDWARS", "Bedwars", "Bed Wars"),
    MURDER_MYSTERY(59, "MURDER_MYSTERY", "MurderMystery", "Murder Mystery"),
    BUILD_BATTLE(60, "BUILD_BATTLE", "BuildBattle", "Build Battle"),
    DUELS(61, "DUELS", "Duels", "Duels"),
    SKYBLOCK(63, "SKYBLOCK", "SkyBlock", "SkyBlock"),
    PIT(64, "PIT", "Pit", "Pit")
}
